name: Build and Push Docker Image

# Controls when the workflow will run
on:
  push:
   tags:
     - '*' # Match tags starting with 'v'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches:
    - main
    - feature/*
    types: [closed] #only when merged happened. Other type: opened=opened, updated=synchronize.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  increase_version:
    runs-on: ubuntu-latest
    steps:
      - name: Increase version
        run: |
          echo "Hit"
